### ISSUE TITLE
Automate LDAP configuration for Jenkins authentication

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/infrastructure#44]
It may be convenient to users to have Jenkins authenticating against company's directory.

We can make LDAP configuration optional in the playbooks by using a control variable in `vars.yaml`, e.g. `ldap_config: yes`.

The following parameters can serve as a baseline and they can be added to `vars.yaml`:

```yaml
ldap_config: yes
ldap_server: "directory.company.com"
ldap_allow_blank_rootdn: yes
ldap_search_base: "ou=directory,o=company.com"
ldap_search_filter: "mail={0}"
```

We can have a task in `roles/jenkins-master/tasks/main.yaml` that only includes `roles/jenkins-master/tasks/ldap_config.yaml` when the variable `ldap_config` is `True`/`Yes`.
